/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bVisitantes;

import Conexion.Conector;
import Inicio.Sesion;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Enumeration;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author ChristianArias
 */
public final class Lista extends javax.swing.JInternalFrame {

    /**
     * Creates new form Lista
     */
    int sel = 0;
    SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
    
    public Lista() {
        initComponents();
        setFrameIcon(new javax.swing.ImageIcon(ClassLoader.getSystemResource("Iconos/visitante.png")));
        setResizable(true);
        setMaximizable(true);
        jDateChooser1.setDate(new other.hora().date());
        jDateChooser2.setDate(new other.hora().date());
        Dimension pantalla = Principal.Escritorio.vPantalla.getSize();
        setSize(pantalla.width-50,300);
        modelo();
        setCellRenderer(jTable1);
        ScheduledExecutorService timer = Executors.newSingleThreadScheduledExecutor();
        timer.scheduleAtFixedRate(tarea, 1, 60, TimeUnit.SECONDS);
        setTitle("Registro provedores "+Sesion.nombreagencia);
        jLabel1.setText(Sesion.nombreagencia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setTitle("Registro de provedores/visitantes");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setToolTipText("Doble click para seleccionar");
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu2.setText("Exportar");

        jMenuItem3.setText("Excel");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenu1.add(jMenu2);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel1))
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Thread(() -> { new other.mostrarFrame().mostrar(new Nuevo(0)); }).start();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        if(jDateChooser1.getDate().before(jDateChooser2.getDate())){
            jTable1.setModel(cargar());
        }else if(jDateChooser1.getDate().equals(jDateChooser2.getDate())){
            jTable1.setModel(cargar());
        }else if(jDateChooser2.getDate().before(jDateChooser1.getDate())){
            Logs.emergente.mostrar("Verifica las fechas fecha inicial es mayor a fecha limite", "Mensaje");
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();
        if(row!=-1){
            sel = Integer.parseInt(String.valueOf(jTable1.getModel().getValueAt(row, 0)));
            switch(evt.getClickCount()){
                case 2:
                switch(col){
                        case 8:
                            actHora();
                            break;
                        default:
                            new Thread(() -> { new other.mostrarFrame().mostrar(new Nuevo(sel)); }).start();
                            break;
                    }
                break;
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jDateChooser1.getDate().before(jDateChooser2.getDate())){
            jTable1.setModel(cargar());
        }else if(jDateChooser1.getDate().equals(jDateChooser2.getDate())){
            jTable1.setModel(cargar());
        }else if(jDateChooser2.getDate().before(jDateChooser1.getDate())){
            Logs.emergente.mostrar("Verifica las fechas fecha inicial es mayor a fecha limite", "Mensaje");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //javax.swing.JTable[] tablas = {jTable1};
        DefaultTableModel[] tablas = {(DefaultTableModel)jTable1.getModel()};
        new other.exportarTxt().exportar(tablas, "Registro de provedoresVisitantes","txt");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public void setCellRenderer(JTable jTable1) {
        Enumeration<TableColumn> en = jTable1.getColumnModel().getColumns();
        while (en.hasMoreElements()) {
            TableColumn tc = en.nextElement();
            tc.setCellRenderer(new other.CellRenderer());
        }
    }
    
    void modelo(){
        /*String titulos[] = {"id","Fecha","Empresa","Visitante","No. Gafette","Departamento","Actividad",
                            "Hora entrada","Hora salida"};*/
        String titulos[] = null ;
        if(Inicio.Sesion.admin){
            titulos = new String[12];
                titulos[0] = "";
                titulos[1] = "Visitante";
                titulos[2] = "Fecha";
                titulos[3] = "Empresa";
                titulos[4] = "No. Gafette";
                titulos[5] = "Departamento";
                titulos[6] = "Actividad";
                titulos[7] = "Hora entrada";
                titulos[8] = "Hora Salida";
                titulos[9] = "Creo";
                titulos[10] = "Actualizo";
                titulos[11] = "Fecha";
        }else{
            titulos = new String[9];
                titulos[0] = "";
                titulos[1] = "Visitante";
                titulos[2] = "Fecha";
                titulos[3] = "Empresa";
                titulos[4] = "No. Gafette";
                titulos[5] = "Departamento";
                titulos[6] = "Actividad";
                titulos[7] = "Hora entrada";
                titulos[8] = "Hora Salida";
        }
        jTable1.setModel(new DefaultTableModel(null,titulos));
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    DefaultTableModel cargar(){
        Connection cn = Conector.conexion();        
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        try{
            String sql = "SELECT * FROM vistaregistrovisitantes WHERE "
                    + "(empresa LIKE ? OR gafette LIKE ? OR nombre LIKE ?) AND fecha BETWEEN ? AND ? AND _agencia LIKE ?";
            
            String [] registros = new String [jTable1.getColumnCount()];
            int x = 0;
            String aux = null;
            model.setRowCount(0);
            PreparedStatement pst = cn.prepareStatement(sql);
                pst.setString(1, "%"+jTextField1.getText()+"%");
                pst.setString(2, "%"+jTextField1.getText()+"%");
                pst.setString(3, "%"+jTextField1.getText()+"%");
                pst.setString(4, String.valueOf(dcn.format(jDateChooser1.getDate())));
                pst.setString(5, String.valueOf(dcn.format(jDateChooser2.getDate())));
                pst.setString(6, "%"+Sesion.nombreagencia+"%");
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("nombre");
                registros[2] = rs.getString("fecha");
                registros[3] = rs.getString("empresa");
                registros[4] = rs.getString("gafette");
                registros[5] = rs.getString("departamento");
                registros[6] = rs.getString("actividad");
                registros[7] = rs.getString("entrada");
                registros[8] = rs.getString("salida");
                if(Inicio.Sesion.admin){
                    registros[9] = rs.getString("creador");
                    registros[10] = rs.getString("editor");
                    registros[11] = rs.getString("fechaAct");
                }
                
                model.addRow(registros);
                x = rs.getRow();
                aux = Integer.toString(x);
            }
            model.fireTableDataChanged();
        }catch(SQLException e){
            new Logs.Error().error(e.getMessage());
        }
        try{
            cn.close();
        }catch(SQLException e){
            new Logs.Error().error(e.getMessage());
        }
        return model;
    }
    
    void actHora(){
        Connection cn = Conector.conexion();
        try{
            String sql = "UPDATE registrovisitantes SET horaSalida = now(),edito = ?,fechaAct = now() WHERE id = ?";
            PreparedStatement pst = cn.prepareStatement(sql);
                pst.setInt(1, Inicio.Sesion.id);
                pst.setInt(2, sel);
            int n = pst.executeUpdate();
            if(n>0){
                Logs.emergente.mostrar("Hora actualizada", "Mensaje");
                jTable1.setModel(cargar());
            }
        }catch(SQLException e){
            new Logs.Error().error(e.getMessage());
        }
        try{
            cn.close();
        }catch(SQLException e){
            new Logs.Error().error(e.getMessage());
        }
    }
    
    public Runnable tarea = () -> { 
        load();
    };
    
    public void load(){
        jTable1.setModel(cargar());
        //System.gc();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
