/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logs;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author ChristianArias
 */
public final class emergente extends javax.swing.JFrame {

    /**
     * Creates new form emergente
     */
    static float opacidad = 0.3f; 
    Thread hilo ;
    static String mnsj = "",titulo = "";
    int tiempo = 5000;
    private SimpleAttributeSet attrib;
    
    public emergente() {
        initComponents();
        hilo = new Thread();
        attrib = new SimpleAttributeSet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextPane1.setEditable(false);
        jTextPane1.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        hilo = new Thread(() -> {
            try {
                ubicacion();
                switch(titulo){
                    case "Error":
                        set_mensaje(1);
                        break;
                    default:
                        set_mensaje(4);
                        break;
                }//new Random().nextInt());
                Thread.sleep(tiempo);
                dispose();
            } catch (InterruptedException ex) {
                Logger.getLogger(emergente.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        hilo.start();
    }//GEN-LAST:event_formWindowOpened

    public static void mostrar(String mensaje, String title){
        emergente e = new emergente();
        mnsj = mensaje;
        titulo = title;
        e.setTitle(titulo);
        e.setSize(300,80);//mensaje.length()*10
        e.setVisible(true);
    }
    
    void set_mensaje(int tipoColor){
        try{
            StyleConstants.setForeground(attrib, getColorTexto(tipoColor));
            SimpleAttributeSet center = new SimpleAttributeSet();
            StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
            StyledDocument sd = jTextPane1.getStyledDocument();
            if (!jTextPane1.getText().isEmpty()) { 
                sd.insertString(sd.getLength(), "", attrib); 
            }
            sd.setParagraphAttributes(0, sd.getLength(), center, false);
            sd.insertString(sd.getLength(), mnsj, attrib);
        }catch (Exception e) { 
            
        } 
    }
    
    void ubicacion(){
        int tamanioX = getWidth(); 
        int tamanioY = getHeight(); 
        int maxX = (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth(); 
        int maxY = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight(); 
        setLocation(maxX - tamanioX - 30 , maxY - tamanioY - 50);         
        repaint(); 
    }
    
    private Color getColorTexto(int tipo) { 
        switch (tipo) { 
            case 0:     // Verde 
                return new Color(0, 130, 0); 
            case 1:     // ROJO 
                return new Color(255, 0, 0);
            case 2:
                return new Color(255,255,0);
            default:    // Negro 
                return new Color(0, 0, 0); 
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emergente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emergente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emergente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emergente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new emergente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
